FLAGS = -Wall --ansi --pedantic -lm -g3 -03

main: ml_lib.o ml_main.o
	gcc ml_main.o ml_lib.o
ml_lib.o: ml_lib.c
	gcc ml_lib.c -o ml_lib.o $(FLAGS)
ml_main.o: ml_main.c
	gcc ml_main.c -o ml_main.o $(FLAGS)